name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11.0.10
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.10'

      - name: Build with Gradle
        run: gradle build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: latest-ci-build
          tag: latest-ci-build
          artifacts: "./dist/gpkg2dxf.zip"
          allowUpdates: true
          replacesArtifacts: true
          artifactContentType: "application/zip"
          token: ${{ secrets.GITHUB_TOKEN }}
